name: RandomX Tests

on:
  push:
    paths:
      - 'mining/randomx/**'
      - 'third_party/randomx/**'
  pull_request:
    paths:
      - 'mining/randomx/**'
      - 'third_party/randomx/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ['1.19', '1.20', '1.21']
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libboost-all-dev
    
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake boost
    
    - name: Build RandomX
      run: |
        cd mining/randomx
        make build-deps
    
    - name: Run tests
      run: |
        cd mining/randomx
        go test -tags cgo -v -short .
    
    - name: Run benchmarks
      run: |
        cd mining/randomx
        go test -tags cgo -bench=. -benchtime=10s 